name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f python/requirements.txt ]; then
          pip install -r python/requirements.txt | echo "skip python/requirements.txt"
        else
          echo "skip python/requirements.txt"
        fi

    - name: Compile the project
      run: |
        python python/main.py 

  test:
    runs-on: ubuntu-latest
    needs: compile

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f python/requirements.txt ]; then
          pip install -r python/requirements.txt | echo "skip python/requirements.txt"
        else
          echo "skip python/requirements.txt"
        fi

    - name: Run tests
      run: |
        python python/unittest_main.py 
